#server配置
server:
  servlet:
    context-path: /
  port: 8082  
#mysql-datasource-config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    ##com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hpf_mysql
    username: root
    password: 1234
  devtools:
    restart:
      enabled: true
#redis连接配置
  redis:
    host: 192.168.88.110
    port: 6379
    password: 
#rabbitmq配置
  rabbitmq:
    host: 192.168.88.111
    port: 5672
    username: guest
    password: guest
    
    
    
#mybatis xml文件扫描位置（sql）
mybatis:
  mapper-locations:
  - classpath:com/example/demo/mapper/*.xml
logging:
  config: classpath:logback-boot.xml
